python main.py -c "Behavioral Science"
python main.py -c "Behavioral Science and Psychology"
python main.py -c "Biomedical and Life Sciences"
python main.py -c "Business and Economics"
python main.py -c "Business and Management"
python main.py -c "Chemistry and Materials Science"
python main.py -c "Computer Science"
python main.py -c "Earth and Environmental Science"
python main.py -c "Economics and Finance"
python main.py -c "Education"
python main.py -c "Energy"
python main.py -c "Engineering"
python main.py -c "Humanities, Social Sciences and Law"
python main.py -c "Intelligent Technologies and Robotics"
python main.py -c "Law and Criminology"
python main.py -c "Literature, Cultural and Media Studies"
python main.py -c "Mathematics and Statistics"
python main.py -c "Medicine"
python main.py -c "Physics and Astronomy"
python main.py -c "Religion and Philosophy"
python main.py -c "Social Sciences"